In [2]:
from matplotlib import pyplot as plt  # data visualization
import numpy as np                    # numerical computations
import pandas as pd                   # dataframes

In [4]:
energy_2023_orig = pd.read_csv("https://raw.github.com/Alissa-Ouspen/data110_alissa/main/datasets/2023_Energy_Benchmarking_MoCo.csv")
energy_2023_orig.head()

,Benchmarking Group,ESPM Property ID,Building Name,Montgomery County Building ID,Reporting Year Start Date,Benchmarking Report Status,Address,City,State,Zip,...,Electricity Use Onsite Renewable (kWh),Natural Gas (therms),Site EUI,Weather-Normalized Site EUI,Source EUI,Weather-Normalized Source EUI,Total GHG Emissions (Metric Tons CO2e),GHG Emissions Intensity (kgCO2e/ft²),Direct GHG Emissions (Metric Tons CO2e),Direct GHG Emissions Intensity (kgCO2e/ft²)
0,County,5244852.0,council office building***,00152444,2016,in compliance,100 maryland ave,rockville,maryland,20850,...,"36,193.6","16,129.2",111.7,114.5,289.4,292.4,"1,219",NaN,85.7,0.7
1,County,5245108.0,grey courthouse*,00152455,2016,in compliance,27 courthouse sq,rockville,maryland,20850,...,0,"11,846.2",50.9,55.0,120.1,124.4,372,NaN,62.9,0.7
2,County,5244851.0,white oak crcc,00278286,2015,in compliance,1700 april ln,silver spring,maryland,20904,...,0,"1,086.9",47.0,47.0,128,128,218.9,NaN,5.8,0.1
3,County,5245118.0,dennis ave health center***,00954308,2015,in compliance,2000 dennis ave,silver spring,maryland,20902,...,0,"38,170.8",122.7,125.8,218.5,219.8,443.1,NaN,202.7,3.8
4,County,20658934.0,wheaton library/ recreation centerc,01093362,2015,in compliance,11701 georgia ave,silver spring,maryland,20902,...,0,"32,603.7",91.9,96.6,180.3,184.1,484.2,NaN,173.2,2.3

In [5]:
energy_2023_orig.describe()

,ESPM Property ID,Reporting Year Start Date,Year Built,Number of Buildings,ENERGY STAR Score,Site EUI,Weather-Normalized Site EUI,GHG Emissions Intensity (kgCO2e/ft²),Direct GHG Emissions Intensity (kgCO2e/ft²)
count,1.321000e+03,1846.000000,1846.000000,1846.000000,1723.000000,1723.000000,1723.000000,0.0,1692.000000
mean,1.887310e+07,2021.343987,1943.508126,2.148429,49.672664,69.067557,72.187522,NaN,1.258310
std,1.481755e+07,3.106473,293.721670,10.217455,37.224617,64.695642,66.236919,NaN,1.820014
min,6.972000e+03,2015.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,5.774982e+06,2017.000000,1970.000000,1.000000,0.000000,35.750000,38.250000,NaN,0.070000
50%,1.647870e+07,2023.000000,1987.500000,1.000000,58.000000,50.300000,53.600000,NaN,0.800000
75%,2.800200e+07,2024.000000,2003.000000,1.000000,84.000000,74.650000,79.000000,NaN,1.600000
max,6.939430e+07,2024.000000,2023.000000,326.000000,100.000000,588.800000,588.800000,NaN,17.000000

In [6]:
energy_2023_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1846 entries, 0 to 1845
Data columns (total 27 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Benchmarking Group                           1846 non-null   object
 1   ESPM Property ID                             1321 non-null   float64
 2   Building Name                                1356 non-null   object
 3   Montgomery County Building ID                1376 non-null   object
 4   Reporting Year Start Date                    1846 non-null   int64
 5   Benchmarking Report Status                   1846 non-null   object
 6   Address                                      1376 non-null   object
 7   City                                         1376 non-null   object
 8   State                                        1808 non-null   object
 9   Zip                                          1846 non-null   object
 10  Year Built                                   1846 non-null   int64
 11  Number of Buildings                          1846 non-null   int64
 12  Primary Property Type Self Selected          1753 non-null   object
 13  Primary Property Type EPA Calculated         1753 non-null   object
 14  Reported Property Gross Floor Area           1753 non-null   object
 15  ENERGY STAR Score                            1723 non-null   float64
 16  Electricity (kWh)                            1723 non-null   object
 17  Electricity Use Onsite Renewable (kWh)       1723 non-null   object
 18  Natural Gas (therms)                         1723 non-null   object
 19  Site EUI                                     1723 non-null   float64
 20  Weather-Normalized Site EUI                  1723 non-null   float64
 21  Source EUI                                   1723 non-null   object
 22  Weather-Normalized Source EUI                1723 non-null   object
 23  Total GHG Emissions (Metric Tons CO2e)       1723 non-null   object
 24  GHG Emissions Intensity (kgCO2e/ft²)         0 non-null      float64
 25  Direct GHG Emissions (Metric Tons CO2e)      1692 non-null   object
 26  Direct GHG Emissions Intensity (kgCO2e/ft²)  1692 non-null   float64
dtypes: float64(6), int64(3), object(18)
memory usage: 389.5+ KB

In [7]:
energy_2023_orig.nunique()

Benchmarking Group                                6
ESPM Property ID                               1321
Building Name                                  1352
Montgomery County Building ID                  1376
Reporting Year Start Date                        10
Benchmarking Report Status                        4
Address                                        1357
City                                             28
State                                             2
Zip                                              44
Year Built                                       99
Number of Buildings                              38
Primary Property Type Self Selected              61
Primary Property Type EPA Calculated             58
Reported Property Gross Floor Area             1672
ENERGY STAR Score                               101
Electricity (kWh)                              1716
Electricity Use Onsite Renewable (kWh)           53
Natural Gas (therms)                           1323
Site EUI                                        919
Weather-Normalized Site EUI                     916
Source EUI                                     1241
Weather-Normalized Source EUI                  1242
Total GHG Emissions (Metric Tons CO2e)         1619
GHG Emissions Intensity (kgCO2e/ft²)              0
Direct GHG Emissions (Metric Tons CO2e)        1127
Direct GHG Emissions Intensity (kgCO2e/ft²)     237
dtype: int64